name: Build and deploy ASP.Net Core app to Azure Web App - BooksReadTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./BooksReadTracker
    environment:
      name: 'Production'
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6EDFB020488043FA9DE917EC99476DEF }} 
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C3F77539BA6B411687D82CCB74111E09 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_15F2A915B0494875AD095A3454E877BC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'booksreadtracker'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
     
