name: Build and deploy ASP.Net Core app to Azure Web App - booksreadtrackermssaccd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Match this version with your project requirements
          include-prerelease: true

      # Ensure the build step uses the correct path to your .sln file
      - name: Build with dotnet
        run: dotnet build BooksReadTracker/BooksReadTracker.sln --configuration Release

      # Ensure the publish step uses the correct path and outputs to the designated folder
      - name: dotnet publish
        run: dotnet publish BooksReadTracker/BooksReadTracker.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'booksreadtrackermssaccd'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp 
          
